BotHunter/Models/Dialog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BotHunter.Models
{
    public class Dialog: Entity
    {
        [Required(ErrorMessage = "Диалог должен иметь название")]
        [DisplayName("Название")]
        public string Name { get; set; }

        [DisplayName("Структура блоков")]
        [AllowHtml]
        public string BlocksXml { get; set; }

        [DisplayName("Сценарий диалога")]
        [AllowHtml]
        public string Aiml { get; set; }
        [DisplayName("Тема")]
        public DialogTopic Topic { get; set; }
        public Guid? TopicId { get; set; }

        static Dialog()
        {
            GetInstance = () => new Dialog();
        }
    }
}

BotHunter/Models/Personality.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace BotHunter.Models
{
        public class Personality: Entity
    {
        [DisplayName("Имя")]
        public string Name { get; set; }
        [DisplayName("Фамилия")]
        public string LastName { get; set; }
        [DisplayName("Электронная почта")]
        public string Email { get; set; }
        [DisplayName("Номер телеграм")]
        public string Telegram { get; set; }
        [DisplayName("Номер телефона")]
        public string Phone { get; set; }

        static Personality()
        {
            GetInstance = () => new Personality();
        }
    }
}

BotHunter/Controllers/HomeController.cs
using BotHunter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Web.Security;
using BotHunter.Models.Infrastructure;

namespace BotHunter.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        DataRepository _DataRepository;
        IAuthorization _AuthorizeHelper;
        public HomeController(DataRepository repository, IAuthorization authorizeHelper)
        {
            _DataRepository = repository;
            _AuthorizeHelper = authorizeHelper;
        }

        public ActionResult Index()
        {
            var currentUser = _AuthorizeHelper.CurrentUser;
            if (currentUser == null)
            {
                return RedirectToAction("Index", "Authorize");
            }
            else
            {
                ViewBag.UserName = currentUser.Name;
                return View();
            }           
        }

        public ActionResult Dialog(Guid? Id = null)
        {
            Dialog dialog = null;
            if (Id != null)
            {
                dialog = _DataRepository.Dialogs.Include(d => d.Creator).FirstOrDefault(d => d.Id == Id.Value);
            }
            if (dialog == null)
            {
                dialog = new Dialog
                {
                    Id = Guid.NewGuid()
                };
            }
            return View(dialog);
        }
        [HttpPost]
        public ActionResult Dialog(Dialog dialog)
        {
            if (ModelState.IsValid)
            {
                var result = _DataRepository.Dialogs.FirstOrDefault(d => d.Id == dialog.Id);
                if (result == null)
                {
                    dialog.CreatedBy(_AuthorizeHelper.CurrentUser);
                    _DataRepository.Dialogs.Add(dialog);
                }
                else
                {
                    result.ChangedBy(_AuthorizeHelper.CurrentUser);
                    result.Name = dialog.Name;
                    result.Aiml = dialog.Aiml;
                    result.BlocksXml = dialog.BlocksXml;
                    result.TopicId = dialog.TopicId;

                    _DataRepository.Dialogs.Attach(result);
                    _DataRepository.Entry(result).State = EntityState.Modified;
                }

                _DataRepository.SaveChanges();

                return RedirectToAction("DialogsList");
            }
            else
            {
                return View(dialog);
            }
        }

        public ActionResult DialogsList()
        {
            IList<Dialog> dialogs = _DataRepository.Dialogs.Include(d => d.Creator).ToList();
            return View(dialogs);
        }

        public ActionResult PersonalitiesList()
        {
            IList<Personality> personalities = _DataRepository.Personalities.ToList();
            return View(personalities);
        }
        public ActionResult Personality(Guid? Id = null)
        {
            Personality personality = null;
            if (Id != null)
            {
                personality = _DataRepository.Personalities.FirstOrDefault(d => d.Id == Id.Value);
            }
            if (personality == null)
            {
                personality = new Personality
                {
                    Id = Guid.NewGuid()
                };
            }
            return View(personality);
        }
        [HttpPost]
        public ActionResult Personality(Personality personality)
        {
            var result = _DataRepository.Personalities.FirstOrDefault(d => d.Id == personality.Id);
            if (result == null)
            {
                personality.CreatedBy(_AuthorizeHelper.CurrentUser);
                _DataRepository.Personalities.Add(personality);
            }
            else
            {
                result.ChangedBy(_AuthorizeHelper.CurrentUser);

                result.Name = personality.Name;
                result.LastName = personality.LastName;
                result.Phone = personality.Phone;
                result.Telegram = personality.Telegram;
                result.Email = personality.Email;

                _DataRepository.Personalities.Attach(result);
                _DataRepository.Entry(result).State = EntityState.Modified;
            }

            _DataRepository.SaveChanges();

            return RedirectToAction("PersonalitiesList");
        }

        public ActionResult SkillsList()
        {
            return View();
        }
    }


}

BotHunter/Controllers/TopicController.cs
using BotHunter.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace BotHunter.Controllers
{
    [Authorize]
    public class TopicController : Controller
    {
        private DataRepository _DataRepository;

        public TopicController(DataRepository dataRepository)
        {
            _DataRepository = dataRepository;
        }

        [HttpPost]
        public JsonResult All()
        {
            return Json(_DataRepository.Topics.
                // возвращаем конфигурацию элемента для jsTree
                Select(t => new {
                    id = t.Id,
                    text = t.Name,
                    parent = (t.Parent == null ? "#" : t.Parent.Id.ToString()),
                    type = t.Type.ToString(),
                    a_attr = t.Description != null ? new { title = t.Description } : null,
                    data = new
                    {
                        Id = t.Id,
                        ParentName = t.Parent.Name,
                        ParentId = t.ParentId,
                        Name = t.Name,
                        Description = t.Description,
                        Type = (int)t.Type
                    }
                })
                .OrderBy(node => node.text)
                .ToArray());
        }

        public PartialViewResult Display(Guid? id = null)
        {
            DialogTopic topic = null;

            if (id != null)
            {
                topic = _DataRepository.Topics.FirstOrDefault(t => t.Id == id);
            }

            if (topic == null)
            {
                topic = new DialogTopic();
            }
            

            return PartialView(topic);
        }

        [HttpPost]
        public JsonResult Edit(DialogTopic topic)
        {
            try
            {
                var record = _DataRepository.Topics.FirstOrDefault(t => t.Id == topic.Id);
                if (record == null)
                {
                    _DataRepository.Topics.Add(topic);
                }
                else
                {
                    record.Name = topic.Name;
                    record.Type = topic.Type;
                    record.Description = topic.Description;

                    _DataRepository.Topics.Attach(record);
                    _DataRepository.Entry(record).State = EntityState.Modified;
                }
                _DataRepository.SaveChanges();
            }
            catch (Exception ex)
            {
                return Json(new { success = false, error = ex.Message });
            }

            return Json(new { success = true });
        }

        [HttpPost]
        public JsonResult Delete(Guid id)
        {
            try
            {
                var topic = new DialogTopic { Id = id };
                _DataRepository.Topics.Attach(topic);
                _DataRepository.Topics.Remove(topic);
                _DataRepository.SaveChanges();
            }
            catch(Exception ex)
            {
                Json(new { success = false, error = ex.Message });
            }

            return Json(new { success = true });
        }
    }
}

BotHunter/Views/Home/Dialog.cshtml
@model BotHunter.Models.Dialog

@{
    ViewBag.Title = "Диалог";
    
}

<h2 class="padding-left-3">Постройте диалог</h2>

@Html.Action("Display", "Topic", new { id = Model.TopicId })


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.TopicId)

        <div class="form-group">
            @Html.LabelFor(model => model.Topic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div id="topics" class="topics-container"></div>
                <div class="row">
                    <a id="addRootTopic" class="button warning">Добавить</a>
                    <a id="deselectTopic" class="button secondary">Снять выделение</a>
                </div>
            </div>
        </div>

        @Html.ValidationSummary(false)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "form-error is-visible" })
            </div>
        </div>

        <div id="blocklyDiv" style="height: 600px; width: 800px;"></div>


        <div class="form-group">
            @Html.LabelFor(model => model.Aiml, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Aiml, new { @class = "codeContainer", id = "aiml-content" })
                @Html.HiddenFor(model => model.BlocksXml, new { id = "blocklyWorkspace" })
                @Html.ValidationMessageFor(model => model.Aiml, "", new { @class = "text-danger" })
                <input id="aiml-edit" class="codeContainer" type="text" value=@Model.Aiml />
            </div>
        </div>

        <div class="form-group margin-top-2">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="button success" />
                @Html.ActionLink("Назад", "DialogsList", null, new { @class = "button" })
            </div>
        </div>
    </div>
}

<div>

</div>
@section TopScripts {
    <script type="text/javascript" src="~/Scripts/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/Scripts/blockly_compressed.js"></script>
    <script type="text/javascript" src="~/Scripts/blockly_javascript.js"></script>
    <script type="text/javascript" src="~/Scripts/blockly_blocks.js"></script>
    <script type="text/javascript" src="~/Scripts/blockly_workspace.js"></script>
    <script type="text/javascript" src="/Scripts/ru.js"></script>
    <script type="text/javascript" src="~/Scripts/ace.js"></script>
    <script type="text/javascript" src="~/Scripts/jstree.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.populate.min.js"></script>
}
@section Scripts {
    <script type="text/javascript" src="~/Scripts/DialogView/blocklysetup.js"></script>
    <script type="text/javascript" src="~/Scripts/DialogView/topic.js"></script>

}
@section Styles {
    <link rel="stylesheet" href="/Content/jquery-ui.css" />
    <link rel="stylesheet" href="~/Content/jstree.css" />
}

BotHunter/Views/Home/DialogsList.cshtml
@model IEnumerable<BotHunter.Models.Dialog>

@{
    ViewBag.Title = "Список диалогов";
}

<h2>Список диалогов</h2>

<p>
    <a class="button success" href="~/Home/Dialog"><i class="fi-plus"></i> Добавить</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Creator)
            </th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "Dialog", new { id = item.Id })
            </td>
            <td>
                @item.Creator.Name
            </td>
            <td>
                @Html.ActionLink("Просмотр", "Dialog", new { id = item.Id }, new { @class = "button" })
                @Html.ActionLink("Удалить", "DialogsList", new { id = item.Id, operation = "delete" }, new { @class = "button alert" })
            </td>
        </tr>
    }

</table>

BotHunter/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная";
}

<h1 id="MainCaption" class="text-center">Редактор Бота</h1>
<div style="height: 50px;"></div>
<section class="row">
    <div class="card columns small-2" style="width: 300px; position: ">
        <div class="card-divider">
            <h4>Привет, @ViewBag.UserName!</h4>
        </div>
        <img src="~/Content/bot.jpg">
        <div class="card-section">
            > Редактируя мои диалоги и настраивая навыки кандидатов, ты поможешь мне быть лучше в своем деле.
        </div>

    </div>
    <article class="columns small-8 right">
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempor orci dapibus ultrices in iaculis nunc sed augue. Aliquam sem et tortor consequat id porta nibh venenatis. Neque aliquam vestibulum morbi blandit cursus risus. Mauris ultrices eros in cursus turpis massa tincidunt dui. Urna porttitor rhoncus dolor purus non enim. Purus non enim praesent elementum facilisis leo vel fringilla est. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Tellus in metus vulputate eu scelerisque felis. Elit pellentesque habitant morbi tristique senectus. Adipiscing at in tellus integer feugiat scelerisque varius. Morbi blandit cursus risus at. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Sem et tortor consequat id porta nibh venenatis. Enim eu turpis egestas pretium aenean pharetra magna ac. Viverra nibh cras pulvinar mattis nunc sed blandit libero. Adipiscing elit pellentesque habitant morbi tristique senectus et netus et. Convallis aenean et tortor at risus viverra adipiscing at. Tristique senectus et netus et malesuada fames ac. A cras semper auctor neque.
        </p>
        Ornare quam viverra orci sagittis. At varius vel pharetra vel turpis nunc eget lorem dolor. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Lorem sed risus ultricies tristique nulla. Amet facilisis magna etiam tempor orci. Nisl rhoncus mattis rhoncus urna neque viverra justo. Dolor sit amet consectetur adipiscing elit ut. Vestibulum lectus mauris ultrices eros. Facilisi etiam dignissim diam quis. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae semper.
        <p>
            Massa tempor nec feugiat nisl pretium fusce id velit. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Dictum at tempor commodo ullamcorper a lacus vestibulum. Tincidunt praesent semper feugiat nibh sed. Euismod lacinia at quis risus sed vulputate odio. Urna condimentum mattis pellentesque id nibh tortor id aliquet lectus. Vel facilisis volutpat est velit. Mollis nunc sed id semper risus in hendrerit. Habitant morbi tristique senectus et netus et. Quis blandit turpis cursus in.
        </p>
        Sit amet mattis vulputate enim nulla aliquet. Sollicitudin aliquam ultrices sagittis orci. Sit amet massa vitae tortor condimentum lacinia quis vel. Ut faucibus pulvinar elementum integer enim neque. Eu ultrices vitae auctor eu augue. Donec pretium vulputate sapien nec. Mollis aliquam ut porttitor leo a. Ut lectus arcu bibendum at varius vel. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. At in tellus integer feugiat scelerisque. Lacinia quis vel eros donec ac odio tempor orci dapibus. Lacus sed turpis tincidunt id aliquet. Diam maecenas ultricies mi eget mauris. Sit amet cursus sit amet dictum sit.
        <p>
            Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. Donec ultrices tincidunt arcu non sodales neque sodales. Posuere lorem ipsum dolor sit amet consectetur adipiscing. Phasellus vestibulum lorem sed risus ultricies tristique nulla. Mauris a diam maecenas sed enim ut. In nibh mauris cursus mattis molestie a iaculis at. Risus nullam eget felis eget nunc lobortis mattis aliquam. Vitae et leo duis ut diam. At imperdiet dui accumsan sit amet nulla facilisi. Laoreet id donec ultrices tincidunt arcu non sodales neque. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin.
        </p>
    </article>
</section>

BotHunter/Views/Home/PersonalitiesList.cshtml
@model IEnumerable<BotHunter.Models.Personality>

@{
    ViewBag.Title = "База кандидатов";
}

<h2>База кандидатов</h2>

<p>
    <a class="button success" href="~/Home/Personality"><i class="fi-plus"></i> Добавить</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Имя
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telegram)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Name + " " + item.LastName, "Personality", new { id = item.Id })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telegram)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Personality", new { id = item.Id }, new { @class = "button" })
                @Html.ActionLink("Удалить", "Delete", new { id = item.Id }, new { @class = "button alert" })
            </td>
        </tr>
    }

</table>

BotHunter/Views/Home/Personality.cshtml
@model BotHunter.Models.Personality

@{
    ViewBag.Title = Model.Name;
}

<h2>Информация о кандидате</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Исправьте или заполните поля:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telegram, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telegram, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telegram, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="button success" />
                @Html.ActionLink("Назад", "PersonalitiesList", null, new { @class = "button"})
            </div>
            
        </div>

    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BotHunter/Views/Home/SkillsList.cshtml
@{
    ViewBag.Title = "Навыки";
}

<h2>Список навыков</h2>

<table class="table" id="jqGridTable"></table>
<div id="jpager"></div>

@section TopScripts{
    <link href="~/Content/themes/base/jquery.ui.all.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-ui-1.10.0.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.jqGrid.js" type="text/javascript"></script>
    <script src="~/Scripts/i18n/grid.locale-ru.js" type="text/javascript"></script>
    <script src="~/Scripts/SkillsView/jqGridSetup.js" type="text/javascript"></script>
}